version: "3.7"

services:

  mongodb:
    image: docker.io/mongo:${MONGO_VERSION}
    hostname: mongodb
    container_name: mongodb
    userns_mode: keep-id
    networks:
      - data_network
    volumes:
      - ${WORK_DIR}/mongodb/db:/data/db:Z
    command:
      - '--quiet'
      - '--bind_ip_all'
      - '--auth'
      - '--enableFreeMonitoring'
      - 'off'
      - '--journal'

  arangodb:
    image: docker.io/arangodb:${ARANGO_VERSION}
    hostname: arangodb
    container_name: arangodb
    userns_mode: keep-id
    networks:
      - data_network
    volumes:
      - ${WORK_DIR}/arangodb/data:/var/lib/arangodb3:Z
      - ${WORK_DIR}/arangodb/apps:/var/lib/arangodb3-apps:Z
    environment:
      - ARANGO_ROOT_PASSWORD=${TEST_PASS}

  elasticsearch:
    image: docker.io/elasticsearch:${ELK_VERSION}
    hostname: elasticsearch01
    container_name: elasticsearch01
    userns_mode: keep-id
    networks:
      - data_network
    volumes:
      - ${WORK_DIR}/elasticsearch/data:/usr/share/elasticsearch/data:Z
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${TEST_PASS}
      - xpack.security.enabled=true

  kibana:
    image: docker.io/kibana:${ELK_VERSION}
    hostname: kibana
    container_name: kibana
    userns_mode: keep-id
    networks:
      - data_network
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch01:${ELASTIC_PORT}
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${TEST_PASS}

  grafana:
    image: docker.io/grafana/grafana:${GRAFANA_VERSION}
    hostname: grafana
    container_name: grafana
    userns_mode: keep-id
    networks:
      - data_network

  nifi:
    image: docker.io/apache/nifi:latest
    hostname: nifi
    container_name: nifi
    userns_mode: keep-id
    networks:
      - data_network
    volumes:
      - ${WORK_DIR}/nifi/content_repository:/opt/nifi/nifi-current/persistent-conf:Z
      - ${WORK_DIR}/nifi/content_repository:/opt/nifi/nifi-current/content_repository:Z
      - ${WORK_DIR}/nifi/database_repository:/opt/nifi/nifi-current/database_repository:Z
      - ${WORK_DIR}/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository:Z
      - ${WORK_DIR}/nifi/logs:/opt/nifi/nifi-current/logs:Z
      - ${WORK_DIR}/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository:Z
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_PORT}
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=${TEST_PASS}

  proxy:
    image: docker.io/traefik:${TRAEFIK_VERSION}
    hostname: proxy
    container_name: proxy
    networks:
      - data_network
    volumes:
      - ${WORK_DIR}/certs/test.crt:/certs/test.crt
      - ${WORK_DIR}/certs/test.key:/certs/test.key
      - ${WORK_DIR}/certs/myCA.pem:/certs/trust.pem
      - ./traefik/config:/etc/traefik/dynamic:Z
      - ./traefik/credentials.txt:/etc/credentials.txt:Z
    ports:
      - ${LISTEN_IP}:${DATA_DASHBOARD_PORT}:${DATA_DASHBOARD_PORT}
      - ${LISTEN_IP}:${MONGO_PORT}:${MONGO_PORT}
      - ${LISTEN_IP}:${ARANGO_PORT}:${ARANGO_PORT}
      - ${LISTEN_IP}:${ELASTIC_PORT}:${ELASTIC_PORT}
      - ${LISTEN_IP}:${KIBANA_PORT}:${KIBANA_PORT}
      - ${LISTEN_IP}:${GRAFANA_PORT}:${GRAFANA_PORT}
      - ${LISTEN_IP}:${NIFI_PORT}:${NIFI_PORT}
    command:
      - '--global.checkNewVersion=false'
      - '--global.sendAnonymousUsage=false'
      - '--accessLog=true'
      - '--accessLog.format=json'
      - '--api=true'
      - '--api.dashboard=true'
      - '--entrypoints.websecure.address=:${DATA_DASHBOARD_PORT}'
      - '--entrypoints.mongo-tcp.address=:${MONGO_PORT}'
      - '--entrypoints.arango-http.address=:${ARANGO_PORT}'
      - '--entrypoints.elasticsearch-http.address=:${ELASTIC_PORT}'
      - '--entrypoints.kibana-http.address=:${KIBANA_PORT}'
      - '--entrypoints.grafana-http.address=:${GRAFANA_PORT}'
      - '--entrypoints.nifi-http.address=:${NIFI_PORT}'
      - '--providers.file.directory=/etc/traefik/dynamic'

networks:
  data_network:
    external: true