apiVersion: v1
kind: ConfigMap
metadata:
  name: data-stack-properties
data:
  ARANGO_PORT: 8529
  ARANGO_VERSION: 3.10.2
  DATA_DASHBOARD_PORT: 8444
  ELASTIC_PORT: 9200
  ELK_VERSION: 8.5.3
  GRAFANA_PORT: 3000
  GRAFANA_VERSION: 9.3.2
  KIBANA_PORT: 5601
  MONGO_PORT: 27017
  MONGO_VERSION: 6.0.3
  NIFI_PORT: 8888
  TEST_PASS: test123
  TRAEFIK_VERSION: 2.9.6
  WORK_DIR: /tmp/data_stack
