apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

generatorOptions:
  disableNameSuffixHash: true

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: data-stack-properties
    path: config-map.yml
